fixtures:
  repositories:
    ssh: "git://github.com/saz/puppet-ssh.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
