---
fixtures:
  repositories:
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    ssh: https://github.com/saz/puppet-ssh.git
    sshkeys_core: https://github.com/puppetlabs/puppetlabs-sshkeys_core.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
